//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooderSupportService.AttachmentsWSProd {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AttachmentsWSProd.AttachmentsServiceProdSoap")]
    public interface AttachmentsServiceProdSoap {
        
        // CODEGEN: Parameter 'UploadDocContentBytes' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadTempAttachmentFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileResponse UploadTempAttachmentFile(FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadTempAttachmentFile", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileResponse> UploadTempAttachmentFileAsync(FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileRequest request);
        
        // CODEGEN: Parameter 'UploadDocContentBytes' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadTempAttachmentFileWithAudit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileWithAuditResponse UploadTempAttachmentFileWithAudit(FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileWithAuditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadTempAttachmentFileWithAudit", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileWithAuditResponse> UploadTempAttachmentFileWithAuditAsync(FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileWithAuditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmTempAttachmentFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        bool ConfirmTempAttachmentFile(string DocID, string ProjectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmTempAttachmentFile", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ConfirmTempAttachmentFileAsync(string DocID, string ProjectName);
        
        // CODEGEN: Parameter 'UploadDocContentBytes' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadConfirmedAttachmentFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        FooderSupportService.AttachmentsWSProd.UploadConfirmedAttachmentFileResponse UploadConfirmedAttachmentFile(FooderSupportService.AttachmentsWSProd.UploadConfirmedAttachmentFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadConfirmedAttachmentFile", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.UploadConfirmedAttachmentFileResponse> UploadConfirmedAttachmentFileAsync(FooderSupportService.AttachmentsWSProd.UploadConfirmedAttachmentFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadAttachmentDoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        FooderSupportService.AttachmentsWSProd.AttachedDocDownloadResult DownloadAttachmentDoc(string DocID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadAttachmentDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.AttachedDocDownloadResult> DownloadAttachmentDocAsync(string DocID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAttachemntFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        FooderSupportService.AttachmentsWSProd.AttachedDocDeleteResult DeleteAttachemntFile(string DocID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAttachemntFile", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.AttachedDocDeleteResult> DeleteAttachemntFileAsync(string DocID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MoveAttachemntFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        FooderSupportService.AttachmentsWSProd.MoveDocumentResult MoveAttachemntFile(FooderSupportService.AttachmentsWSProd.MoveDocToNewFNEnvParams moveParamas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MoveAttachemntFile", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.MoveDocumentResult> MoveAttachemntFileAsync(FooderSupportService.AttachmentsWSProd.MoveDocToNewFNEnvParams moveParamas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createThumbnail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        FooderSupportService.AttachmentsWSProd.AttachedDocThumbnailResult createThumbnail(string originalDocID, string thumbSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createThumbnail", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.AttachedDocThumbnailResult> createThumbnailAsync(string originalDocID, string thumbSize);
        
        // CODEGEN: Parameter 'UploadDocContentBytes' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadAttachmentFileWithProperties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        FooderSupportService.AttachmentsWSProd.UploadAttachmentFileWithPropertiesResponse UploadAttachmentFileWithProperties(FooderSupportService.AttachmentsWSProd.UploadAttachmentFileWithPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadAttachmentFileWithProperties", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.UploadAttachmentFileWithPropertiesResponse> UploadAttachmentFileWithPropertiesAsync(FooderSupportService.AttachmentsWSProd.UploadAttachmentFileWithPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadUPDAInfraAttachmentProperties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        FooderSupportService.AttachmentsWSProd.UPDA_InfrStructure_DocClass_Props DownloadUPDAInfraAttachmentProperties(string DocID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadUPDAInfraAttachmentProperties", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.UPDA_InfrStructure_DocClass_Props> DownloadUPDAInfraAttachmentPropertiesAsync(string DocID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAttachmentTrackRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        bool AddAttachmentTrackRecord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAttachmentTrackRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddAttachmentTrackRecordAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTrackAttachmentRecords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        FooderSupportService.AttachmentsWSProd.FN_ATTCHMNT_SRVC_MNTR[] GetTrackAttachmentRecords(string fnDocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTrackAttachmentRecords", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.FN_ATTCHMNT_SRVC_MNTR[]> GetTrackAttachmentRecordsAsync(string fnDocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetViewAttachmentWebPageUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        string GetViewAttachmentWebPageUrl();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetViewAttachmentWebPageUrl", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetViewAttachmentWebPageUrlAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTrackAttachmentWebPageUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        string GetTrackAttachmentWebPageUrl();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTrackAttachmentWebPageUrl", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetTrackAttachmentWebPageUrlAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AttachedDocUploadResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool boolFinalResultField;
        
        private string newCreatedDocIDField;
        
        private string strFNExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool boolFinalResult {
            get {
                return this.boolFinalResultField;
            }
            set {
                this.boolFinalResultField = value;
                this.RaisePropertyChanged("boolFinalResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string newCreatedDocID {
            get {
                return this.newCreatedDocIDField;
            }
            set {
                this.newCreatedDocIDField = value;
                this.RaisePropertyChanged("newCreatedDocID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string strFNException {
            get {
                return this.strFNExceptionField;
            }
            set {
                this.strFNExceptionField = value;
                this.RaisePropertyChanged("strFNException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
                this.RaisePropertyChanged("EntitySetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
                this.RaisePropertyChanged("EntityContainerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
                this.RaisePropertyChanged("EntityKeyValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FN_ATTCHMNT_SRVC_MNTR))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
                this.RaisePropertyChanged("EntityKey");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FN_ATTCHMNT_SRVC_MNTR : EntityObject {
        
        private string fN_DOC_IDField;
        
        private string pROJECT_NAMEField;
        
        private string oPERATION_TYPEField;
        
        private string oPERATION_DATEField;
        
        private decimal idField;
        
        private string dOC_TITLEField;
        
        private string dOC_MIMETYPEField;
        
        private string dOC_CLASSField;
        
        private System.Nullable<decimal> fILE_SIZEField;
        
        private string fN_USERField;
        
        private string fN_OBJECTSTOREField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FN_DOC_ID {
            get {
                return this.fN_DOC_IDField;
            }
            set {
                this.fN_DOC_IDField = value;
                this.RaisePropertyChanged("FN_DOC_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PROJECT_NAME {
            get {
                return this.pROJECT_NAMEField;
            }
            set {
                this.pROJECT_NAMEField = value;
                this.RaisePropertyChanged("PROJECT_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OPERATION_TYPE {
            get {
                return this.oPERATION_TYPEField;
            }
            set {
                this.oPERATION_TYPEField = value;
                this.RaisePropertyChanged("OPERATION_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OPERATION_DATE {
            get {
                return this.oPERATION_DATEField;
            }
            set {
                this.oPERATION_DATEField = value;
                this.RaisePropertyChanged("OPERATION_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DOC_TITLE {
            get {
                return this.dOC_TITLEField;
            }
            set {
                this.dOC_TITLEField = value;
                this.RaisePropertyChanged("DOC_TITLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DOC_MIMETYPE {
            get {
                return this.dOC_MIMETYPEField;
            }
            set {
                this.dOC_MIMETYPEField = value;
                this.RaisePropertyChanged("DOC_MIMETYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DOC_CLASS {
            get {
                return this.dOC_CLASSField;
            }
            set {
                this.dOC_CLASSField = value;
                this.RaisePropertyChanged("DOC_CLASS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> FILE_SIZE {
            get {
                return this.fILE_SIZEField;
            }
            set {
                this.fILE_SIZEField = value;
                this.RaisePropertyChanged("FILE_SIZE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FN_USER {
            get {
                return this.fN_USERField;
            }
            set {
                this.fN_USERField = value;
                this.RaisePropertyChanged("FN_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string FN_OBJECTSTORE {
            get {
                return this.fN_OBJECTSTOREField;
            }
            set {
                this.fN_OBJECTSTOREField = value;
                this.RaisePropertyChanged("FN_OBJECTSTORE");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UPDA_InfrStructure_DocClass_Props : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strTest1_PropField;
        
        private string strTest2_PropField;
        
        private string strTest3_PropField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string strTest1_Prop {
            get {
                return this.strTest1_PropField;
            }
            set {
                this.strTest1_PropField = value;
                this.RaisePropertyChanged("strTest1_Prop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string strTest2_Prop {
            get {
                return this.strTest2_PropField;
            }
            set {
                this.strTest2_PropField = value;
                this.RaisePropertyChanged("strTest2_Prop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string strTest3_Prop {
            get {
                return this.strTest3_PropField;
            }
            set {
                this.strTest3_PropField = value;
                this.RaisePropertyChanged("strTest3_Prop");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AttachedDocThumbnailResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string newCreatedDocIDField;
        
        private bool boolFinalResultField;
        
        private string downloadDocMimeTypeField;
        
        private byte[] thumbContentBytesField;
        
        private string strFNExceptionField;
        
        private string fN_DocTitleField;
        
        private string fN_DocClassField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string newCreatedDocID {
            get {
                return this.newCreatedDocIDField;
            }
            set {
                this.newCreatedDocIDField = value;
                this.RaisePropertyChanged("newCreatedDocID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool boolFinalResult {
            get {
                return this.boolFinalResultField;
            }
            set {
                this.boolFinalResultField = value;
                this.RaisePropertyChanged("boolFinalResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string downloadDocMimeType {
            get {
                return this.downloadDocMimeTypeField;
            }
            set {
                this.downloadDocMimeTypeField = value;
                this.RaisePropertyChanged("downloadDocMimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] thumbContentBytes {
            get {
                return this.thumbContentBytesField;
            }
            set {
                this.thumbContentBytesField = value;
                this.RaisePropertyChanged("thumbContentBytes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string strFNException {
            get {
                return this.strFNExceptionField;
            }
            set {
                this.strFNExceptionField = value;
                this.RaisePropertyChanged("strFNException");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FN_DocTitle {
            get {
                return this.fN_DocTitleField;
            }
            set {
                this.fN_DocTitleField = value;
                this.RaisePropertyChanged("FN_DocTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FN_DocClass {
            get {
                return this.fN_DocClassField;
            }
            set {
                this.fN_DocClassField = value;
                this.RaisePropertyChanged("FN_DocClass");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MoveDocumentResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool boolFinalResultField;
        
        private string newCreatedDocIDField;
        
        private string strFNExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool boolFinalResult {
            get {
                return this.boolFinalResultField;
            }
            set {
                this.boolFinalResultField = value;
                this.RaisePropertyChanged("boolFinalResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string newCreatedDocID {
            get {
                return this.newCreatedDocIDField;
            }
            set {
                this.newCreatedDocIDField = value;
                this.RaisePropertyChanged("newCreatedDocID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string strFNException {
            get {
                return this.strFNExceptionField;
            }
            set {
                this.strFNExceptionField = value;
                this.RaisePropertyChanged("strFNException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MoveDocToNewFNEnvParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string old_FN_UriField;
        
        private string oldFN_UserNameField;
        
        private string oldFN_PasswordField;
        
        private string oldFN_ObjectStoreNameField;
        
        private string old_FN_DocIDField;
        
        private string new_FN_UriField;
        
        private string newFN_UserNameField;
        
        private string newFN_PasswordField;
        
        private string newFN_ObjectStoreNameField;
        
        private string caller_ProjectNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Old_FN_Uri {
            get {
                return this.old_FN_UriField;
            }
            set {
                this.old_FN_UriField = value;
                this.RaisePropertyChanged("Old_FN_Uri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OldFN_UserName {
            get {
                return this.oldFN_UserNameField;
            }
            set {
                this.oldFN_UserNameField = value;
                this.RaisePropertyChanged("OldFN_UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OldFN_Password {
            get {
                return this.oldFN_PasswordField;
            }
            set {
                this.oldFN_PasswordField = value;
                this.RaisePropertyChanged("OldFN_Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OldFN_ObjectStoreName {
            get {
                return this.oldFN_ObjectStoreNameField;
            }
            set {
                this.oldFN_ObjectStoreNameField = value;
                this.RaisePropertyChanged("OldFN_ObjectStoreName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Old_FN_DocID {
            get {
                return this.old_FN_DocIDField;
            }
            set {
                this.old_FN_DocIDField = value;
                this.RaisePropertyChanged("Old_FN_DocID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string New_FN_Uri {
            get {
                return this.new_FN_UriField;
            }
            set {
                this.new_FN_UriField = value;
                this.RaisePropertyChanged("New_FN_Uri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NewFN_UserName {
            get {
                return this.newFN_UserNameField;
            }
            set {
                this.newFN_UserNameField = value;
                this.RaisePropertyChanged("NewFN_UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string NewFN_Password {
            get {
                return this.newFN_PasswordField;
            }
            set {
                this.newFN_PasswordField = value;
                this.RaisePropertyChanged("NewFN_Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string NewFN_ObjectStoreName {
            get {
                return this.newFN_ObjectStoreNameField;
            }
            set {
                this.newFN_ObjectStoreNameField = value;
                this.RaisePropertyChanged("NewFN_ObjectStoreName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Caller_ProjectName {
            get {
                return this.caller_ProjectNameField;
            }
            set {
                this.caller_ProjectNameField = value;
                this.RaisePropertyChanged("Caller_ProjectName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AttachedDocDeleteResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool boolFinalResultField;
        
        private string strFNExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool boolFinalResult {
            get {
                return this.boolFinalResultField;
            }
            set {
                this.boolFinalResultField = value;
                this.RaisePropertyChanged("boolFinalResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string strFNException {
            get {
                return this.strFNExceptionField;
            }
            set {
                this.strFNExceptionField = value;
                this.RaisePropertyChanged("strFNException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AttachedDocDownloadResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool boolFinalResultField;
        
        private string downloadDocMimeTypeField;
        
        private byte[] docContentBytesField;
        
        private string strFNExceptionField;
        
        private string fN_DocTitleField;
        
        private string fN_DocClassField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool boolFinalResult {
            get {
                return this.boolFinalResultField;
            }
            set {
                this.boolFinalResultField = value;
                this.RaisePropertyChanged("boolFinalResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string downloadDocMimeType {
            get {
                return this.downloadDocMimeTypeField;
            }
            set {
                this.downloadDocMimeTypeField = value;
                this.RaisePropertyChanged("downloadDocMimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] docContentBytes {
            get {
                return this.docContentBytesField;
            }
            set {
                this.docContentBytesField = value;
                this.RaisePropertyChanged("docContentBytes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string strFNException {
            get {
                return this.strFNExceptionField;
            }
            set {
                this.strFNExceptionField = value;
                this.RaisePropertyChanged("strFNException");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FN_DocTitle {
            get {
                return this.fN_DocTitleField;
            }
            set {
                this.fN_DocTitleField = value;
                this.RaisePropertyChanged("FN_DocTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FN_DocClass {
            get {
                return this.fN_DocClassField;
            }
            set {
                this.fN_DocClassField = value;
                this.RaisePropertyChanged("FN_DocClass");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadTempAttachmentFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadTempAttachmentFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DocTitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string DocMimeType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ProjectName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] UploadDocContentBytes;
        
        public UploadTempAttachmentFileRequest() {
        }
        
        public UploadTempAttachmentFileRequest(string DocTitle, string DocMimeType, string ProjectName, byte[] UploadDocContentBytes) {
            this.DocTitle = DocTitle;
            this.DocMimeType = DocMimeType;
            this.ProjectName = ProjectName;
            this.UploadDocContentBytes = UploadDocContentBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadTempAttachmentFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadTempAttachmentFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.AttachmentsWSProd.AttachedDocUploadResult UploadTempAttachmentFileResult;
        
        public UploadTempAttachmentFileResponse() {
        }
        
        public UploadTempAttachmentFileResponse(FooderSupportService.AttachmentsWSProd.AttachedDocUploadResult UploadTempAttachmentFileResult) {
            this.UploadTempAttachmentFileResult = UploadTempAttachmentFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadTempAttachmentFileWithAudit", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadTempAttachmentFileWithAuditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DocTitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string DocMimeType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ProjectName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ActionUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] UploadDocContentBytes;
        
        public UploadTempAttachmentFileWithAuditRequest() {
        }
        
        public UploadTempAttachmentFileWithAuditRequest(string DocTitle, string DocMimeType, string ProjectName, string ActionUser, byte[] UploadDocContentBytes) {
            this.DocTitle = DocTitle;
            this.DocMimeType = DocMimeType;
            this.ProjectName = ProjectName;
            this.ActionUser = ActionUser;
            this.UploadDocContentBytes = UploadDocContentBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadTempAttachmentFileWithAuditResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadTempAttachmentFileWithAuditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.AttachmentsWSProd.AttachedDocUploadResult UploadTempAttachmentFileWithAuditResult;
        
        public UploadTempAttachmentFileWithAuditResponse() {
        }
        
        public UploadTempAttachmentFileWithAuditResponse(FooderSupportService.AttachmentsWSProd.AttachedDocUploadResult UploadTempAttachmentFileWithAuditResult) {
            this.UploadTempAttachmentFileWithAuditResult = UploadTempAttachmentFileWithAuditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadConfirmedAttachmentFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadConfirmedAttachmentFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DocTitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string DocMimeType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ProjectName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] UploadDocContentBytes;
        
        public UploadConfirmedAttachmentFileRequest() {
        }
        
        public UploadConfirmedAttachmentFileRequest(string DocTitle, string DocMimeType, string ProjectName, byte[] UploadDocContentBytes) {
            this.DocTitle = DocTitle;
            this.DocMimeType = DocMimeType;
            this.ProjectName = ProjectName;
            this.UploadDocContentBytes = UploadDocContentBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadConfirmedAttachmentFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadConfirmedAttachmentFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.AttachmentsWSProd.AttachedDocUploadResult UploadConfirmedAttachmentFileResult;
        
        public UploadConfirmedAttachmentFileResponse() {
        }
        
        public UploadConfirmedAttachmentFileResponse(FooderSupportService.AttachmentsWSProd.AttachedDocUploadResult UploadConfirmedAttachmentFileResult) {
            this.UploadConfirmedAttachmentFileResult = UploadConfirmedAttachmentFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadAttachmentFileWithProperties", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadAttachmentFileWithPropertiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DocTitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string DocClass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string DocMimeType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ProjectName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] UploadDocContentBytes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public FooderSupportService.AttachmentsWSProd.UPDA_InfrStructure_DocClass_Props UPDA_InfrStructure_DocClass_Props;
        
        public UploadAttachmentFileWithPropertiesRequest() {
        }
        
        public UploadAttachmentFileWithPropertiesRequest(string DocTitle, string DocClass, string DocMimeType, string ProjectName, byte[] UploadDocContentBytes, FooderSupportService.AttachmentsWSProd.UPDA_InfrStructure_DocClass_Props UPDA_InfrStructure_DocClass_Props) {
            this.DocTitle = DocTitle;
            this.DocClass = DocClass;
            this.DocMimeType = DocMimeType;
            this.ProjectName = ProjectName;
            this.UploadDocContentBytes = UploadDocContentBytes;
            this.UPDA_InfrStructure_DocClass_Props = UPDA_InfrStructure_DocClass_Props;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadAttachmentFileWithPropertiesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadAttachmentFileWithPropertiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.AttachmentsWSProd.AttachedDocUploadResult UploadAttachmentFileWithPropertiesResult;
        
        public UploadAttachmentFileWithPropertiesResponse() {
        }
        
        public UploadAttachmentFileWithPropertiesResponse(FooderSupportService.AttachmentsWSProd.AttachedDocUploadResult UploadAttachmentFileWithPropertiesResult) {
            this.UploadAttachmentFileWithPropertiesResult = UploadAttachmentFileWithPropertiesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AttachmentsServiceProdSoapChannel : FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AttachmentsServiceProdSoapClient : System.ServiceModel.ClientBase<FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap>, FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap {
        
        public AttachmentsServiceProdSoapClient() {
        }
        
        public AttachmentsServiceProdSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AttachmentsServiceProdSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttachmentsServiceProdSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttachmentsServiceProdSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileResponse FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap.UploadTempAttachmentFile(FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileRequest request) {
            return base.Channel.UploadTempAttachmentFile(request);
        }
        
        public FooderSupportService.AttachmentsWSProd.AttachedDocUploadResult UploadTempAttachmentFile(string DocTitle, string DocMimeType, string ProjectName, byte[] UploadDocContentBytes) {
            FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileRequest inValue = new FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileRequest();
            inValue.DocTitle = DocTitle;
            inValue.DocMimeType = DocMimeType;
            inValue.ProjectName = ProjectName;
            inValue.UploadDocContentBytes = UploadDocContentBytes;
            FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileResponse retVal = ((FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap)(this)).UploadTempAttachmentFile(inValue);
            return retVal.UploadTempAttachmentFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileResponse> FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap.UploadTempAttachmentFileAsync(FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileRequest request) {
            return base.Channel.UploadTempAttachmentFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileResponse> UploadTempAttachmentFileAsync(string DocTitle, string DocMimeType, string ProjectName, byte[] UploadDocContentBytes) {
            FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileRequest inValue = new FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileRequest();
            inValue.DocTitle = DocTitle;
            inValue.DocMimeType = DocMimeType;
            inValue.ProjectName = ProjectName;
            inValue.UploadDocContentBytes = UploadDocContentBytes;
            return ((FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap)(this)).UploadTempAttachmentFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileWithAuditResponse FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap.UploadTempAttachmentFileWithAudit(FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileWithAuditRequest request) {
            return base.Channel.UploadTempAttachmentFileWithAudit(request);
        }
        
        public FooderSupportService.AttachmentsWSProd.AttachedDocUploadResult UploadTempAttachmentFileWithAudit(string DocTitle, string DocMimeType, string ProjectName, string ActionUser, byte[] UploadDocContentBytes) {
            FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileWithAuditRequest inValue = new FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileWithAuditRequest();
            inValue.DocTitle = DocTitle;
            inValue.DocMimeType = DocMimeType;
            inValue.ProjectName = ProjectName;
            inValue.ActionUser = ActionUser;
            inValue.UploadDocContentBytes = UploadDocContentBytes;
            FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileWithAuditResponse retVal = ((FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap)(this)).UploadTempAttachmentFileWithAudit(inValue);
            return retVal.UploadTempAttachmentFileWithAuditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileWithAuditResponse> FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap.UploadTempAttachmentFileWithAuditAsync(FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileWithAuditRequest request) {
            return base.Channel.UploadTempAttachmentFileWithAuditAsync(request);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileWithAuditResponse> UploadTempAttachmentFileWithAuditAsync(string DocTitle, string DocMimeType, string ProjectName, string ActionUser, byte[] UploadDocContentBytes) {
            FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileWithAuditRequest inValue = new FooderSupportService.AttachmentsWSProd.UploadTempAttachmentFileWithAuditRequest();
            inValue.DocTitle = DocTitle;
            inValue.DocMimeType = DocMimeType;
            inValue.ProjectName = ProjectName;
            inValue.ActionUser = ActionUser;
            inValue.UploadDocContentBytes = UploadDocContentBytes;
            return ((FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap)(this)).UploadTempAttachmentFileWithAuditAsync(inValue);
        }
        
        public bool ConfirmTempAttachmentFile(string DocID, string ProjectName) {
            return base.Channel.ConfirmTempAttachmentFile(DocID, ProjectName);
        }
        
        public System.Threading.Tasks.Task<bool> ConfirmTempAttachmentFileAsync(string DocID, string ProjectName) {
            return base.Channel.ConfirmTempAttachmentFileAsync(DocID, ProjectName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FooderSupportService.AttachmentsWSProd.UploadConfirmedAttachmentFileResponse FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap.UploadConfirmedAttachmentFile(FooderSupportService.AttachmentsWSProd.UploadConfirmedAttachmentFileRequest request) {
            return base.Channel.UploadConfirmedAttachmentFile(request);
        }
        
        public FooderSupportService.AttachmentsWSProd.AttachedDocUploadResult UploadConfirmedAttachmentFile(string DocTitle, string DocMimeType, string ProjectName, byte[] UploadDocContentBytes) {
            FooderSupportService.AttachmentsWSProd.UploadConfirmedAttachmentFileRequest inValue = new FooderSupportService.AttachmentsWSProd.UploadConfirmedAttachmentFileRequest();
            inValue.DocTitle = DocTitle;
            inValue.DocMimeType = DocMimeType;
            inValue.ProjectName = ProjectName;
            inValue.UploadDocContentBytes = UploadDocContentBytes;
            FooderSupportService.AttachmentsWSProd.UploadConfirmedAttachmentFileResponse retVal = ((FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap)(this)).UploadConfirmedAttachmentFile(inValue);
            return retVal.UploadConfirmedAttachmentFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.UploadConfirmedAttachmentFileResponse> FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap.UploadConfirmedAttachmentFileAsync(FooderSupportService.AttachmentsWSProd.UploadConfirmedAttachmentFileRequest request) {
            return base.Channel.UploadConfirmedAttachmentFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.UploadConfirmedAttachmentFileResponse> UploadConfirmedAttachmentFileAsync(string DocTitle, string DocMimeType, string ProjectName, byte[] UploadDocContentBytes) {
            FooderSupportService.AttachmentsWSProd.UploadConfirmedAttachmentFileRequest inValue = new FooderSupportService.AttachmentsWSProd.UploadConfirmedAttachmentFileRequest();
            inValue.DocTitle = DocTitle;
            inValue.DocMimeType = DocMimeType;
            inValue.ProjectName = ProjectName;
            inValue.UploadDocContentBytes = UploadDocContentBytes;
            return ((FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap)(this)).UploadConfirmedAttachmentFileAsync(inValue);
        }
        
        public FooderSupportService.AttachmentsWSProd.AttachedDocDownloadResult DownloadAttachmentDoc(string DocID) {
            return base.Channel.DownloadAttachmentDoc(DocID);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.AttachedDocDownloadResult> DownloadAttachmentDocAsync(string DocID) {
            return base.Channel.DownloadAttachmentDocAsync(DocID);
        }
        
        public FooderSupportService.AttachmentsWSProd.AttachedDocDeleteResult DeleteAttachemntFile(string DocID) {
            return base.Channel.DeleteAttachemntFile(DocID);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.AttachedDocDeleteResult> DeleteAttachemntFileAsync(string DocID) {
            return base.Channel.DeleteAttachemntFileAsync(DocID);
        }
        
        public FooderSupportService.AttachmentsWSProd.MoveDocumentResult MoveAttachemntFile(FooderSupportService.AttachmentsWSProd.MoveDocToNewFNEnvParams moveParamas) {
            return base.Channel.MoveAttachemntFile(moveParamas);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.MoveDocumentResult> MoveAttachemntFileAsync(FooderSupportService.AttachmentsWSProd.MoveDocToNewFNEnvParams moveParamas) {
            return base.Channel.MoveAttachemntFileAsync(moveParamas);
        }
        
        public FooderSupportService.AttachmentsWSProd.AttachedDocThumbnailResult createThumbnail(string originalDocID, string thumbSize) {
            return base.Channel.createThumbnail(originalDocID, thumbSize);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.AttachedDocThumbnailResult> createThumbnailAsync(string originalDocID, string thumbSize) {
            return base.Channel.createThumbnailAsync(originalDocID, thumbSize);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FooderSupportService.AttachmentsWSProd.UploadAttachmentFileWithPropertiesResponse FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap.UploadAttachmentFileWithProperties(FooderSupportService.AttachmentsWSProd.UploadAttachmentFileWithPropertiesRequest request) {
            return base.Channel.UploadAttachmentFileWithProperties(request);
        }
        
        public FooderSupportService.AttachmentsWSProd.AttachedDocUploadResult UploadAttachmentFileWithProperties(string DocTitle, string DocClass, string DocMimeType, string ProjectName, byte[] UploadDocContentBytes, FooderSupportService.AttachmentsWSProd.UPDA_InfrStructure_DocClass_Props UPDA_InfrStructure_DocClass_Props) {
            FooderSupportService.AttachmentsWSProd.UploadAttachmentFileWithPropertiesRequest inValue = new FooderSupportService.AttachmentsWSProd.UploadAttachmentFileWithPropertiesRequest();
            inValue.DocTitle = DocTitle;
            inValue.DocClass = DocClass;
            inValue.DocMimeType = DocMimeType;
            inValue.ProjectName = ProjectName;
            inValue.UploadDocContentBytes = UploadDocContentBytes;
            inValue.UPDA_InfrStructure_DocClass_Props = UPDA_InfrStructure_DocClass_Props;
            FooderSupportService.AttachmentsWSProd.UploadAttachmentFileWithPropertiesResponse retVal = ((FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap)(this)).UploadAttachmentFileWithProperties(inValue);
            return retVal.UploadAttachmentFileWithPropertiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.UploadAttachmentFileWithPropertiesResponse> FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap.UploadAttachmentFileWithPropertiesAsync(FooderSupportService.AttachmentsWSProd.UploadAttachmentFileWithPropertiesRequest request) {
            return base.Channel.UploadAttachmentFileWithPropertiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.UploadAttachmentFileWithPropertiesResponse> UploadAttachmentFileWithPropertiesAsync(string DocTitle, string DocClass, string DocMimeType, string ProjectName, byte[] UploadDocContentBytes, FooderSupportService.AttachmentsWSProd.UPDA_InfrStructure_DocClass_Props UPDA_InfrStructure_DocClass_Props) {
            FooderSupportService.AttachmentsWSProd.UploadAttachmentFileWithPropertiesRequest inValue = new FooderSupportService.AttachmentsWSProd.UploadAttachmentFileWithPropertiesRequest();
            inValue.DocTitle = DocTitle;
            inValue.DocClass = DocClass;
            inValue.DocMimeType = DocMimeType;
            inValue.ProjectName = ProjectName;
            inValue.UploadDocContentBytes = UploadDocContentBytes;
            inValue.UPDA_InfrStructure_DocClass_Props = UPDA_InfrStructure_DocClass_Props;
            return ((FooderSupportService.AttachmentsWSProd.AttachmentsServiceProdSoap)(this)).UploadAttachmentFileWithPropertiesAsync(inValue);
        }
        
        public FooderSupportService.AttachmentsWSProd.UPDA_InfrStructure_DocClass_Props DownloadUPDAInfraAttachmentProperties(string DocID) {
            return base.Channel.DownloadUPDAInfraAttachmentProperties(DocID);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.UPDA_InfrStructure_DocClass_Props> DownloadUPDAInfraAttachmentPropertiesAsync(string DocID) {
            return base.Channel.DownloadUPDAInfraAttachmentPropertiesAsync(DocID);
        }
        
        public bool AddAttachmentTrackRecord() {
            return base.Channel.AddAttachmentTrackRecord();
        }
        
        public System.Threading.Tasks.Task<bool> AddAttachmentTrackRecordAsync() {
            return base.Channel.AddAttachmentTrackRecordAsync();
        }
        
        public FooderSupportService.AttachmentsWSProd.FN_ATTCHMNT_SRVC_MNTR[] GetTrackAttachmentRecords(string fnDocId) {
            return base.Channel.GetTrackAttachmentRecords(fnDocId);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.AttachmentsWSProd.FN_ATTCHMNT_SRVC_MNTR[]> GetTrackAttachmentRecordsAsync(string fnDocId) {
            return base.Channel.GetTrackAttachmentRecordsAsync(fnDocId);
        }
        
        public string GetViewAttachmentWebPageUrl() {
            return base.Channel.GetViewAttachmentWebPageUrl();
        }
        
        public System.Threading.Tasks.Task<string> GetViewAttachmentWebPageUrlAsync() {
            return base.Channel.GetViewAttachmentWebPageUrlAsync();
        }
        
        public string GetTrackAttachmentWebPageUrl() {
            return base.Channel.GetTrackAttachmentWebPageUrl();
        }
        
        public System.Threading.Tasks.Task<string> GetTrackAttachmentWebPageUrlAsync() {
            return base.Channel.GetTrackAttachmentWebPageUrlAsync();
        }
    }
}
