//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooderSupportService.Moi_IntegrationServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Moi_IntegrationServices.Msi_IntegrationWSSoap")]
    public interface Msi_IntegrationWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersonInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MoiExceptionBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WsResponseDTOsBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WsRequestDTOsBase))]
        FooderSupportService.Moi_IntegrationServices.PersonInfoWsResponseDto GetPersonInfo(FooderSupportService.Moi_IntegrationServices.PersonInfoWsRequestParamsDto personInfoWsRequestParamsDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersonInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.Moi_IntegrationServices.PersonInfoWsResponseDto> GetPersonInfoAsync(FooderSupportService.Moi_IntegrationServices.PersonInfoWsRequestParamsDto personInfoWsRequestParamsDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSponsorInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MoiExceptionBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WsResponseDTOsBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WsRequestDTOsBase))]
        FooderSupportService.Moi_IntegrationServices.SponsorInfoWsResponseDto GetSponsorInfo(FooderSupportService.Moi_IntegrationServices.PersonInfoWsRequestParamsDto personInfoWsRequestParamsDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSponsorInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.Moi_IntegrationServices.SponsorInfoWsResponseDto> GetSponsorInfoAsync(FooderSupportService.Moi_IntegrationServices.PersonInfoWsRequestParamsDto personInfoWsRequestParamsDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompanyInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MoiExceptionBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WsResponseDTOsBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WsRequestDTOsBase))]
        FooderSupportService.Moi_IntegrationServices.CompanyInfoWsResponseDto GetCompanyInfo(FooderSupportService.Moi_IntegrationServices.CompanyInfoWsRequestParamsDto companyInfoWsRequestParamsDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompanyInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.Moi_IntegrationServices.CompanyInfoWsResponseDto> GetCompanyInfoAsync(FooderSupportService.Moi_IntegrationServices.CompanyInfoWsRequestParamsDto companyInfoWsRequestParamsDto);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonInfoWsRequestParamsDto : WsRequestDTOsBase {
        
        private string qidField;
        
        private System.DateTime idCardExpDateField;
        
        private string appUserNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Qid {
            get {
                return this.qidField;
            }
            set {
                this.qidField = value;
                this.RaisePropertyChanged("Qid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime IdCardExpDate {
            get {
                return this.idCardExpDateField;
            }
            set {
                this.idCardExpDateField = value;
                this.RaisePropertyChanged("IdCardExpDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AppUserName {
            get {
                return this.appUserNameField;
            }
            set {
                this.appUserNameField = value;
                this.RaisePropertyChanged("AppUserName");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyInfoWsRequestParamsDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonInfoWsRequestParamsDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WsRequestDTOsBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ejb.msi.moi.gov.qa/")]
    public partial class authorizedDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authorizedNameField;
        
        private string authorizedQidNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string authorizedName {
            get {
                return this.authorizedNameField;
            }
            set {
                this.authorizedNameField = value;
                this.RaisePropertyChanged("authorizedName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string authorizedQidNum {
            get {
                return this.authorizedQidNumField;
            }
            set {
                this.authorizedQidNumField = value;
                this.RaisePropertyChanged("authorizedQidNum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CompanyInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cpyNumField;
        
        private string cpyBrNumField;
        
        private string cpyTypField;
        
        private string cpyArbNameField;
        
        private string cpyEngNameField;
        
        private System.Nullable<System.DateTime> cpyStrDateField;
        
        private System.Nullable<System.DateTime> cpyExpDateField;
        
        private string cpyStatusCodeField;
        
        private System.Nullable<System.DateTime> cpyStatusDateField;
        
        private string sectorArabicDescriptionField;
        
        private string sectorEnglishDescriptionField;
        
        private authorizedDTO[] authorizedPersonsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CpyNum {
            get {
                return this.cpyNumField;
            }
            set {
                this.cpyNumField = value;
                this.RaisePropertyChanged("CpyNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CpyBrNum {
            get {
                return this.cpyBrNumField;
            }
            set {
                this.cpyBrNumField = value;
                this.RaisePropertyChanged("CpyBrNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CpyTyp {
            get {
                return this.cpyTypField;
            }
            set {
                this.cpyTypField = value;
                this.RaisePropertyChanged("CpyTyp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CpyArbName {
            get {
                return this.cpyArbNameField;
            }
            set {
                this.cpyArbNameField = value;
                this.RaisePropertyChanged("CpyArbName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CpyEngName {
            get {
                return this.cpyEngNameField;
            }
            set {
                this.cpyEngNameField = value;
                this.RaisePropertyChanged("CpyEngName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> CpyStrDate {
            get {
                return this.cpyStrDateField;
            }
            set {
                this.cpyStrDateField = value;
                this.RaisePropertyChanged("CpyStrDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> CpyExpDate {
            get {
                return this.cpyExpDateField;
            }
            set {
                this.cpyExpDateField = value;
                this.RaisePropertyChanged("CpyExpDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CpyStatusCode {
            get {
                return this.cpyStatusCodeField;
            }
            set {
                this.cpyStatusCodeField = value;
                this.RaisePropertyChanged("CpyStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> CpyStatusDate {
            get {
                return this.cpyStatusDateField;
            }
            set {
                this.cpyStatusDateField = value;
                this.RaisePropertyChanged("CpyStatusDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SectorArabicDescription {
            get {
                return this.sectorArabicDescriptionField;
            }
            set {
                this.sectorArabicDescriptionField = value;
                this.RaisePropertyChanged("SectorArabicDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SectorEnglishDescription {
            get {
                return this.sectorEnglishDescriptionField;
            }
            set {
                this.sectorEnglishDescriptionField = value;
                this.RaisePropertyChanged("SectorEnglishDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public authorizedDTO[] AuthorizedPersons {
            get {
                return this.authorizedPersonsField;
            }
            set {
                this.authorizedPersonsField = value;
                this.RaisePropertyChanged("AuthorizedPersons");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ejb.msi.moi.gov.qa/")]
    public partial class sponsorDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sponArabNameField;
        
        private string sponCompanyBrnNumField;
        
        private string sponCompanyNumField;
        
        private string sponCompanyTypeField;
        
        private string sponEngNameField;
        
        private string sponQIDNumField;
        
        private string sponRelationField;
        
        private string sponRelationDescField;
        
        private string sponSponQIDNumField;
        
        private string sponTypeField;
        
        private string sponTypeDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sponArabName {
            get {
                return this.sponArabNameField;
            }
            set {
                this.sponArabNameField = value;
                this.RaisePropertyChanged("sponArabName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sponCompanyBrnNum {
            get {
                return this.sponCompanyBrnNumField;
            }
            set {
                this.sponCompanyBrnNumField = value;
                this.RaisePropertyChanged("sponCompanyBrnNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sponCompanyNum {
            get {
                return this.sponCompanyNumField;
            }
            set {
                this.sponCompanyNumField = value;
                this.RaisePropertyChanged("sponCompanyNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sponCompanyType {
            get {
                return this.sponCompanyTypeField;
            }
            set {
                this.sponCompanyTypeField = value;
                this.RaisePropertyChanged("sponCompanyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string sponEngName {
            get {
                return this.sponEngNameField;
            }
            set {
                this.sponEngNameField = value;
                this.RaisePropertyChanged("sponEngName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sponQIDNum {
            get {
                return this.sponQIDNumField;
            }
            set {
                this.sponQIDNumField = value;
                this.RaisePropertyChanged("sponQIDNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string sponRelation {
            get {
                return this.sponRelationField;
            }
            set {
                this.sponRelationField = value;
                this.RaisePropertyChanged("sponRelation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string sponRelationDesc {
            get {
                return this.sponRelationDescField;
            }
            set {
                this.sponRelationDescField = value;
                this.RaisePropertyChanged("sponRelationDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string sponSponQIDNum {
            get {
                return this.sponSponQIDNumField;
            }
            set {
                this.sponSponQIDNumField = value;
                this.RaisePropertyChanged("sponSponQIDNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string sponType {
            get {
                return this.sponTypeField;
            }
            set {
                this.sponTypeField = value;
                this.RaisePropertyChanged("sponType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string sponTypeDesc {
            get {
                return this.sponTypeDescField;
            }
            set {
                this.sponTypeDescField = value;
                this.RaisePropertyChanged("sponTypeDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string qidField;
        
        private string personTypeField;
        
        private string arbName1Field;
        
        private string arbName2Field;
        
        private string arbName3Field;
        
        private string arbName4Field;
        
        private string engName1Field;
        
        private string arbName5Field;
        
        private string engName2Field;
        
        private string engName3Field;
        
        private string engName4Field;
        
        private string engName5Field;
        
        private string natCodeField;
        
        private string sexField;
        
        private System.Nullable<System.DateTime> birthDateField;
        
        private string statusField;
        
        private System.Nullable<System.DateTime> statusDateField;
        
        private string natCodeTextENField;
        
        private string natCodeTextARField;
        
        private System.Nullable<System.DateTime> residencyIssueDateField;
        
        private System.Nullable<System.DateTime> residencyExpiryDateField;
        
        private System.Nullable<System.DateTime> idExpiryDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Qid {
            get {
                return this.qidField;
            }
            set {
                this.qidField = value;
                this.RaisePropertyChanged("Qid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PersonType {
            get {
                return this.personTypeField;
            }
            set {
                this.personTypeField = value;
                this.RaisePropertyChanged("PersonType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ArbName1 {
            get {
                return this.arbName1Field;
            }
            set {
                this.arbName1Field = value;
                this.RaisePropertyChanged("ArbName1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ArbName2 {
            get {
                return this.arbName2Field;
            }
            set {
                this.arbName2Field = value;
                this.RaisePropertyChanged("ArbName2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ArbName3 {
            get {
                return this.arbName3Field;
            }
            set {
                this.arbName3Field = value;
                this.RaisePropertyChanged("ArbName3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ArbName4 {
            get {
                return this.arbName4Field;
            }
            set {
                this.arbName4Field = value;
                this.RaisePropertyChanged("ArbName4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string EngName1 {
            get {
                return this.engName1Field;
            }
            set {
                this.engName1Field = value;
                this.RaisePropertyChanged("EngName1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ArbName5 {
            get {
                return this.arbName5Field;
            }
            set {
                this.arbName5Field = value;
                this.RaisePropertyChanged("ArbName5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string EngName2 {
            get {
                return this.engName2Field;
            }
            set {
                this.engName2Field = value;
                this.RaisePropertyChanged("EngName2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EngName3 {
            get {
                return this.engName3Field;
            }
            set {
                this.engName3Field = value;
                this.RaisePropertyChanged("EngName3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string EngName4 {
            get {
                return this.engName4Field;
            }
            set {
                this.engName4Field = value;
                this.RaisePropertyChanged("EngName4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string EngName5 {
            get {
                return this.engName5Field;
            }
            set {
                this.engName5Field = value;
                this.RaisePropertyChanged("EngName5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string NatCode {
            get {
                return this.natCodeField;
            }
            set {
                this.natCodeField = value;
                this.RaisePropertyChanged("NatCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
                this.RaisePropertyChanged("Sex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<System.DateTime> StatusDate {
            get {
                return this.statusDateField;
            }
            set {
                this.statusDateField = value;
                this.RaisePropertyChanged("StatusDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string NatCodeTextEN {
            get {
                return this.natCodeTextENField;
            }
            set {
                this.natCodeTextENField = value;
                this.RaisePropertyChanged("NatCodeTextEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string NatCodeTextAR {
            get {
                return this.natCodeTextARField;
            }
            set {
                this.natCodeTextARField = value;
                this.RaisePropertyChanged("NatCodeTextAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<System.DateTime> ResidencyIssueDate {
            get {
                return this.residencyIssueDateField;
            }
            set {
                this.residencyIssueDateField = value;
                this.RaisePropertyChanged("ResidencyIssueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<System.DateTime> ResidencyExpiryDate {
            get {
                return this.residencyExpiryDateField;
            }
            set {
                this.residencyExpiryDateField = value;
                this.RaisePropertyChanged("ResidencyExpiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<System.DateTime> IdExpiryDate {
            get {
                return this.idExpiryDateField;
            }
            set {
                this.idExpiryDateField = value;
                this.RaisePropertyChanged("IdExpiryDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MsiException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MoiExceptionBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int mmeErrorCodeField;
        
        private string mmeArErrorDescField;
        
        private string mmeEnErrorDescField;
        
        private string moiErrorCodeField;
        
        private string moiArErrorDescField;
        
        private string moiEnErrorDescField;
        
        private string detErrorDescField;
        
        private string gdxDetErrorDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MmeErrorCode {
            get {
                return this.mmeErrorCodeField;
            }
            set {
                this.mmeErrorCodeField = value;
                this.RaisePropertyChanged("MmeErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MmeArErrorDesc {
            get {
                return this.mmeArErrorDescField;
            }
            set {
                this.mmeArErrorDescField = value;
                this.RaisePropertyChanged("MmeArErrorDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MmeEnErrorDesc {
            get {
                return this.mmeEnErrorDescField;
            }
            set {
                this.mmeEnErrorDescField = value;
                this.RaisePropertyChanged("MmeEnErrorDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MoiErrorCode {
            get {
                return this.moiErrorCodeField;
            }
            set {
                this.moiErrorCodeField = value;
                this.RaisePropertyChanged("MoiErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MoiArErrorDesc {
            get {
                return this.moiArErrorDescField;
            }
            set {
                this.moiArErrorDescField = value;
                this.RaisePropertyChanged("MoiArErrorDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MoiEnErrorDesc {
            get {
                return this.moiEnErrorDescField;
            }
            set {
                this.moiEnErrorDescField = value;
                this.RaisePropertyChanged("MoiEnErrorDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DetErrorDesc {
            get {
                return this.detErrorDescField;
            }
            set {
                this.detErrorDescField = value;
                this.RaisePropertyChanged("DetErrorDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string GdxDetErrorDesc {
            get {
                return this.gdxDetErrorDescField;
            }
            set {
                this.gdxDetErrorDescField = value;
                this.RaisePropertyChanged("GdxDetErrorDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsiException : MoiExceptionBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyInfoWsResponseDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SponsorInfoWsResponseDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonInfoWsResponseDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WsResponseDTOsBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isOperationSuccessField;
        
        private int totalNoOfRecordsField;
        
        private bool isErrFromMmeSideField;
        
        private bool isErrFromMoiSideField;
        
        private bool isErrFromGdxSideField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsOperationSuccess {
            get {
                return this.isOperationSuccessField;
            }
            set {
                this.isOperationSuccessField = value;
                this.RaisePropertyChanged("IsOperationSuccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TotalNoOfRecords {
            get {
                return this.totalNoOfRecordsField;
            }
            set {
                this.totalNoOfRecordsField = value;
                this.RaisePropertyChanged("TotalNoOfRecords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsErrFromMmeSide {
            get {
                return this.isErrFromMmeSideField;
            }
            set {
                this.isErrFromMmeSideField = value;
                this.RaisePropertyChanged("IsErrFromMmeSide");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsErrFromMoiSide {
            get {
                return this.isErrFromMoiSideField;
            }
            set {
                this.isErrFromMoiSideField = value;
                this.RaisePropertyChanged("IsErrFromMoiSide");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsErrFromGdxSide {
            get {
                return this.isErrFromGdxSideField;
            }
            set {
                this.isErrFromGdxSideField = value;
                this.RaisePropertyChanged("IsErrFromGdxSide");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CompanyInfoWsResponseDto : WsResponseDTOsBase {
        
        private MsiException msiExceptionField;
        
        private CompanyInfo companyInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MsiException MsiException {
            get {
                return this.msiExceptionField;
            }
            set {
                this.msiExceptionField = value;
                this.RaisePropertyChanged("MsiException");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CompanyInfo CompanyInfo {
            get {
                return this.companyInfoField;
            }
            set {
                this.companyInfoField = value;
                this.RaisePropertyChanged("CompanyInfo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SponsorInfoWsResponseDto : WsResponseDTOsBase {
        
        private MsiException msiExceptionField;
        
        private sponsorDTO sponsorInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MsiException MsiException {
            get {
                return this.msiExceptionField;
            }
            set {
                this.msiExceptionField = value;
                this.RaisePropertyChanged("MsiException");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public sponsorDTO SponsorInfo {
            get {
                return this.sponsorInfoField;
            }
            set {
                this.sponsorInfoField = value;
                this.RaisePropertyChanged("SponsorInfo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonInfoWsResponseDto : WsResponseDTOsBase {
        
        private MsiException msiExceptionField;
        
        private PersonInfo personInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MsiException MsiException {
            get {
                return this.msiExceptionField;
            }
            set {
                this.msiExceptionField = value;
                this.RaisePropertyChanged("MsiException");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PersonInfo PersonInfo {
            get {
                return this.personInfoField;
            }
            set {
                this.personInfoField = value;
                this.RaisePropertyChanged("PersonInfo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CompanyInfoWsRequestParamsDto : WsRequestDTOsBase {
        
        private string cpyTypeField;
        
        private string cpyNumField;
        
        private string cpyBrnNumField;
        
        private System.DateTime idCardExpDateField;
        
        private string appUserNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CpyType {
            get {
                return this.cpyTypeField;
            }
            set {
                this.cpyTypeField = value;
                this.RaisePropertyChanged("CpyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CpyNum {
            get {
                return this.cpyNumField;
            }
            set {
                this.cpyNumField = value;
                this.RaisePropertyChanged("CpyNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CpyBrnNum {
            get {
                return this.cpyBrnNumField;
            }
            set {
                this.cpyBrnNumField = value;
                this.RaisePropertyChanged("CpyBrnNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime IdCardExpDate {
            get {
                return this.idCardExpDateField;
            }
            set {
                this.idCardExpDateField = value;
                this.RaisePropertyChanged("IdCardExpDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AppUserName {
            get {
                return this.appUserNameField;
            }
            set {
                this.appUserNameField = value;
                this.RaisePropertyChanged("AppUserName");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Msi_IntegrationWSSoapChannel : FooderSupportService.Moi_IntegrationServices.Msi_IntegrationWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Msi_IntegrationWSSoapClient : System.ServiceModel.ClientBase<FooderSupportService.Moi_IntegrationServices.Msi_IntegrationWSSoap>, FooderSupportService.Moi_IntegrationServices.Msi_IntegrationWSSoap {
        
        public Msi_IntegrationWSSoapClient() {
        }
        
        public Msi_IntegrationWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Msi_IntegrationWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Msi_IntegrationWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Msi_IntegrationWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FooderSupportService.Moi_IntegrationServices.PersonInfoWsResponseDto GetPersonInfo(FooderSupportService.Moi_IntegrationServices.PersonInfoWsRequestParamsDto personInfoWsRequestParamsDto) {
            return base.Channel.GetPersonInfo(personInfoWsRequestParamsDto);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.Moi_IntegrationServices.PersonInfoWsResponseDto> GetPersonInfoAsync(FooderSupportService.Moi_IntegrationServices.PersonInfoWsRequestParamsDto personInfoWsRequestParamsDto) {
            return base.Channel.GetPersonInfoAsync(personInfoWsRequestParamsDto);
        }
        
        public FooderSupportService.Moi_IntegrationServices.SponsorInfoWsResponseDto GetSponsorInfo(FooderSupportService.Moi_IntegrationServices.PersonInfoWsRequestParamsDto personInfoWsRequestParamsDto) {
            return base.Channel.GetSponsorInfo(personInfoWsRequestParamsDto);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.Moi_IntegrationServices.SponsorInfoWsResponseDto> GetSponsorInfoAsync(FooderSupportService.Moi_IntegrationServices.PersonInfoWsRequestParamsDto personInfoWsRequestParamsDto) {
            return base.Channel.GetSponsorInfoAsync(personInfoWsRequestParamsDto);
        }
        
        public FooderSupportService.Moi_IntegrationServices.CompanyInfoWsResponseDto GetCompanyInfo(FooderSupportService.Moi_IntegrationServices.CompanyInfoWsRequestParamsDto companyInfoWsRequestParamsDto) {
            return base.Channel.GetCompanyInfo(companyInfoWsRequestParamsDto);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.Moi_IntegrationServices.CompanyInfoWsResponseDto> GetCompanyInfoAsync(FooderSupportService.Moi_IntegrationServices.CompanyInfoWsRequestParamsDto companyInfoWsRequestParamsDto) {
            return base.Channel.GetCompanyInfoAsync(companyInfoWsRequestParamsDto);
        }
    }
}
