//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooderSupportService.MobileVerification {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:baladiya.gov.qa/customerVerificationmobile/ws/v1_0", ConfigurationName="MobileVerification.CustomerVerificationMobile")]
    public interface CustomerVerificationMobile {
        
        // CODEGEN: Generating message contract since the operation verifyCustomerMobile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="verifyCustomerMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FooderSupportService.MobileVerification.validateCustomerResponse verifyCustomerMobile(FooderSupportService.MobileVerification.VerifyCustomerMobileRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="verifyCustomerMobile", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.MobileVerification.validateCustomerResponse> verifyCustomerMobileAsync(FooderSupportService.MobileVerification.VerifyCustomerMobileRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:baladiya.gov.qa/customerVerificationmobile/ws/v1_0")]
    public partial class VerificationCustomerMobile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VerifyCustomerMobileRequest verifyCustomerMobileRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public VerifyCustomerMobileRequest verifyCustomerMobileRequest {
            get {
                return this.verifyCustomerMobileRequestField;
            }
            set {
                this.verifyCustomerMobileRequestField = value;
                this.RaisePropertyChanged("verifyCustomerMobileRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:baladiya.gov.qa/customerVerificationmobile/schemas/v1_0")]
    public partial class VerifyCustomerMobileRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string qIDField;
        
        private string mobileNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string QID {
            get {
                return this.qIDField;
            }
            set {
                this.qIDField = value;
                this.RaisePropertyChanged("QID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
                this.RaisePropertyChanged("mobileNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:baladiya.gov.qa/customerVerificationmobile/schemas/v1_0")]
    public partial class VerifyCustomerMobileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool statusField;
        
        private string statusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string statusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("statusMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:baladiya.gov.qa/customerVerificationmobile/ws/v1_0")]
    public partial class VerificationCustomerMobileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VerifyCustomerMobileResponse resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public VerifyCustomerMobileResponse result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyCustomerMobileRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:baladiya.gov.qa/customerVerificationmobile/ws/v1_0", Order=0)]
        public FooderSupportService.MobileVerification.VerificationCustomerMobile VerificationCustomerMobile;
        
        public VerifyCustomerMobileRequest1() {
        }
        
        public VerifyCustomerMobileRequest1(FooderSupportService.MobileVerification.VerificationCustomerMobile VerificationCustomerMobile) {
            this.VerificationCustomerMobile = VerificationCustomerMobile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:baladiya.gov.qa/customerVerificationmobile/ws/v1_0", Order=0)]
        public FooderSupportService.MobileVerification.VerificationCustomerMobileResponse VerificationCustomerMobileResponse;
        
        public validateCustomerResponse() {
        }
        
        public validateCustomerResponse(FooderSupportService.MobileVerification.VerificationCustomerMobileResponse VerificationCustomerMobileResponse) {
            this.VerificationCustomerMobileResponse = VerificationCustomerMobileResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerVerificationMobileChannel : FooderSupportService.MobileVerification.CustomerVerificationMobile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerVerificationMobileClient : System.ServiceModel.ClientBase<FooderSupportService.MobileVerification.CustomerVerificationMobile>, FooderSupportService.MobileVerification.CustomerVerificationMobile {
        
        public CustomerVerificationMobileClient() {
        }
        
        public CustomerVerificationMobileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerVerificationMobileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerVerificationMobileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerVerificationMobileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FooderSupportService.MobileVerification.validateCustomerResponse FooderSupportService.MobileVerification.CustomerVerificationMobile.verifyCustomerMobile(FooderSupportService.MobileVerification.VerifyCustomerMobileRequest1 request) {
            return base.Channel.verifyCustomerMobile(request);
        }
        
        public FooderSupportService.MobileVerification.VerificationCustomerMobileResponse verifyCustomerMobile(FooderSupportService.MobileVerification.VerificationCustomerMobile VerificationCustomerMobile) {
            FooderSupportService.MobileVerification.VerifyCustomerMobileRequest1 inValue = new FooderSupportService.MobileVerification.VerifyCustomerMobileRequest1();
            inValue.VerificationCustomerMobile = VerificationCustomerMobile;
            FooderSupportService.MobileVerification.validateCustomerResponse retVal = ((FooderSupportService.MobileVerification.CustomerVerificationMobile)(this)).verifyCustomerMobile(inValue);
            return retVal.VerificationCustomerMobileResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FooderSupportService.MobileVerification.validateCustomerResponse> FooderSupportService.MobileVerification.CustomerVerificationMobile.verifyCustomerMobileAsync(FooderSupportService.MobileVerification.VerifyCustomerMobileRequest1 request) {
            return base.Channel.verifyCustomerMobileAsync(request);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.MobileVerification.validateCustomerResponse> verifyCustomerMobileAsync(FooderSupportService.MobileVerification.VerificationCustomerMobile VerificationCustomerMobile) {
            FooderSupportService.MobileVerification.VerifyCustomerMobileRequest1 inValue = new FooderSupportService.MobileVerification.VerifyCustomerMobileRequest1();
            inValue.VerificationCustomerMobile = VerificationCustomerMobile;
            return ((FooderSupportService.MobileVerification.CustomerVerificationMobile)(this)).verifyCustomerMobileAsync(inValue);
        }
    }
}
