//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooderSupportService.SMSWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSWebService.CommunicateSoap")]
    public interface CommunicateSoap {
        
        // CODEGEN: Generating message contract since element name QID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send_Email", ReplyAction="*")]
        FooderSupportService.SMSWebService.Send_EmailResponse Send_Email(FooderSupportService.SMSWebService.Send_EmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send_Email", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Send_EmailResponse> Send_EmailAsync(FooderSupportService.SMSWebService.Send_EmailRequest request);
        
        // CODEGEN: Generating message contract since element name QID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send_normal_SMS", ReplyAction="*")]
        FooderSupportService.SMSWebService.Send_normal_SMSResponse Send_normal_SMS(FooderSupportService.SMSWebService.Send_normal_SMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send_normal_SMS", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Send_normal_SMSResponse> Send_normal_SMSAsync(FooderSupportService.SMSWebService.Send_normal_SMSRequest request);
        
        // CODEGEN: Generating message contract since element name QID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send_normal_SMS_ooredoo", ReplyAction="*")]
        FooderSupportService.SMSWebService.Send_normal_SMS_ooredooResponse Send_normal_SMS_ooredoo(FooderSupportService.SMSWebService.Send_normal_SMS_ooredooRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send_normal_SMS_ooredoo", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Send_normal_SMS_ooredooResponse> Send_normal_SMS_ooredooAsync(FooderSupportService.SMSWebService.Send_normal_SMS_ooredooRequest request);
        
        // CODEGEN: Generating message contract since element name QID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send_normal_SMS_Employees", ReplyAction="*")]
        FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesResponse Send_normal_SMS_Employees(FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send_normal_SMS_Employees", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesResponse> Send_normal_SMS_EmployeesAsync(FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name QID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send_normal_SMS_ooredoo_Emp", ReplyAction="*")]
        FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpResponse Send_normal_SMS_ooredoo_Emp(FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send_normal_SMS_ooredoo_Emp", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpResponse> Send_normal_SMS_ooredoo_EmpAsync(FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpRequest request);
        
        // CODEGEN: Generating message contract since element name QID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create_Send_Otp_OOredOO", ReplyAction="*")]
        FooderSupportService.SMSWebService.Create_Send_Otp_OOredOOResponse Create_Send_Otp_OOredOO(FooderSupportService.SMSWebService.Create_Send_Otp_OOredOORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create_Send_Otp_OOredOO", ReplyAction="*")]
        System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Create_Send_Otp_OOredOOResponse> Create_Send_Otp_OOredOOAsync(FooderSupportService.SMSWebService.Create_Send_Otp_OOredOORequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send_EmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send_Email", Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.SMSWebService.Send_EmailRequestBody Body;
        
        public Send_EmailRequest() {
        }
        
        public Send_EmailRequest(FooderSupportService.SMSWebService.Send_EmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send_EmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string App_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Sent_by;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string To_Emails_List;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Cc_Email_List;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email_Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Email_Body;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string My_Attached_File;
        
        public Send_EmailRequestBody() {
        }
        
        public Send_EmailRequestBody(string QID, string App_type, string Sent_by, string To_Emails_List, string Cc_Email_List, string Email_Subject, string Email_Body, string My_Attached_File) {
            this.QID = QID;
            this.App_type = App_type;
            this.Sent_by = Sent_by;
            this.To_Emails_List = To_Emails_List;
            this.Cc_Email_List = Cc_Email_List;
            this.Email_Subject = Email_Subject;
            this.Email_Body = Email_Body;
            this.My_Attached_File = My_Attached_File;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send_EmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send_EmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.SMSWebService.Send_EmailResponseBody Body;
        
        public Send_EmailResponse() {
        }
        
        public Send_EmailResponse(FooderSupportService.SMSWebService.Send_EmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send_EmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Send_EmailResult;
        
        public Send_EmailResponseBody() {
        }
        
        public Send_EmailResponseBody(string Send_EmailResult) {
            this.Send_EmailResult = Send_EmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send_normal_SMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send_normal_SMS", Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.SMSWebService.Send_normal_SMSRequestBody Body;
        
        public Send_normal_SMSRequest() {
        }
        
        public Send_normal_SMSRequest(FooderSupportService.SMSWebService.Send_normal_SMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send_normal_SMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string App_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public FooderSupportService.SMSWebService.ArrayOfString mobile_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Sent_by;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Txt_sms;
        
        public Send_normal_SMSRequestBody() {
        }
        
        public Send_normal_SMSRequestBody(string QID, string App_type, FooderSupportService.SMSWebService.ArrayOfString mobile_no, string Sent_by, string Txt_sms) {
            this.QID = QID;
            this.App_type = App_type;
            this.mobile_no = mobile_no;
            this.Sent_by = Sent_by;
            this.Txt_sms = Txt_sms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send_normal_SMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send_normal_SMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.SMSWebService.Send_normal_SMSResponseBody Body;
        
        public Send_normal_SMSResponse() {
        }
        
        public Send_normal_SMSResponse(FooderSupportService.SMSWebService.Send_normal_SMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send_normal_SMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Send_normal_SMSResult;
        
        public Send_normal_SMSResponseBody() {
        }
        
        public Send_normal_SMSResponseBody(string Send_normal_SMSResult) {
            this.Send_normal_SMSResult = Send_normal_SMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send_normal_SMS_ooredooRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send_normal_SMS_ooredoo", Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.SMSWebService.Send_normal_SMS_ooredooRequestBody Body;
        
        public Send_normal_SMS_ooredooRequest() {
        }
        
        public Send_normal_SMS_ooredooRequest(FooderSupportService.SMSWebService.Send_normal_SMS_ooredooRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send_normal_SMS_ooredooRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string App_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobile_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Sent_by;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Txt_sms;
        
        public Send_normal_SMS_ooredooRequestBody() {
        }
        
        public Send_normal_SMS_ooredooRequestBody(string QID, string App_type, string mobile_no, string Sent_by, string Txt_sms) {
            this.QID = QID;
            this.App_type = App_type;
            this.mobile_no = mobile_no;
            this.Sent_by = Sent_by;
            this.Txt_sms = Txt_sms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send_normal_SMS_ooredooResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send_normal_SMS_ooredooResponse", Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.SMSWebService.Send_normal_SMS_ooredooResponseBody Body;
        
        public Send_normal_SMS_ooredooResponse() {
        }
        
        public Send_normal_SMS_ooredooResponse(FooderSupportService.SMSWebService.Send_normal_SMS_ooredooResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send_normal_SMS_ooredooResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Send_normal_SMS_ooredooResult;
        
        public Send_normal_SMS_ooredooResponseBody() {
        }
        
        public Send_normal_SMS_ooredooResponseBody(string Send_normal_SMS_ooredooResult) {
            this.Send_normal_SMS_ooredooResult = Send_normal_SMS_ooredooResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send_normal_SMS_EmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send_normal_SMS_Employees", Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesRequestBody Body;
        
        public Send_normal_SMS_EmployeesRequest() {
        }
        
        public Send_normal_SMS_EmployeesRequest(FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send_normal_SMS_EmployeesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string App_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Emp_Qid_sapno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Sent_by;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Txt_sms;
        
        public Send_normal_SMS_EmployeesRequestBody() {
        }
        
        public Send_normal_SMS_EmployeesRequestBody(string QID, string App_type, string Emp_Qid_sapno, string Sent_by, string Txt_sms) {
            this.QID = QID;
            this.App_type = App_type;
            this.Emp_Qid_sapno = Emp_Qid_sapno;
            this.Sent_by = Sent_by;
            this.Txt_sms = Txt_sms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send_normal_SMS_EmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send_normal_SMS_EmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesResponseBody Body;
        
        public Send_normal_SMS_EmployeesResponse() {
        }
        
        public Send_normal_SMS_EmployeesResponse(FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send_normal_SMS_EmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Send_normal_SMS_EmployeesResult;
        
        public Send_normal_SMS_EmployeesResponseBody() {
        }
        
        public Send_normal_SMS_EmployeesResponseBody(string Send_normal_SMS_EmployeesResult) {
            this.Send_normal_SMS_EmployeesResult = Send_normal_SMS_EmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send_normal_SMS_ooredoo_EmpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send_normal_SMS_ooredoo_Emp", Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpRequestBody Body;
        
        public Send_normal_SMS_ooredoo_EmpRequest() {
        }
        
        public Send_normal_SMS_ooredoo_EmpRequest(FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send_normal_SMS_ooredoo_EmpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string App_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string QID_Sap;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Sent_by;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Txt_sms;
        
        public Send_normal_SMS_ooredoo_EmpRequestBody() {
        }
        
        public Send_normal_SMS_ooredoo_EmpRequestBody(string QID, string App_type, string QID_Sap, string Sent_by, string Txt_sms) {
            this.QID = QID;
            this.App_type = App_type;
            this.QID_Sap = QID_Sap;
            this.Sent_by = Sent_by;
            this.Txt_sms = Txt_sms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send_normal_SMS_ooredoo_EmpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send_normal_SMS_ooredoo_EmpResponse", Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpResponseBody Body;
        
        public Send_normal_SMS_ooredoo_EmpResponse() {
        }
        
        public Send_normal_SMS_ooredoo_EmpResponse(FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send_normal_SMS_ooredoo_EmpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Send_normal_SMS_ooredoo_EmpResult;
        
        public Send_normal_SMS_ooredoo_EmpResponseBody() {
        }
        
        public Send_normal_SMS_ooredoo_EmpResponseBody(string Send_normal_SMS_ooredoo_EmpResult) {
            this.Send_normal_SMS_ooredoo_EmpResult = Send_normal_SMS_ooredoo_EmpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Create_Send_Otp_OOredOORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create_Send_Otp_OOredOO", Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.SMSWebService.Create_Send_Otp_OOredOORequestBody Body;
        
        public Create_Send_Otp_OOredOORequest() {
        }
        
        public Create_Send_Otp_OOredOORequest(FooderSupportService.SMSWebService.Create_Send_Otp_OOredOORequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Create_Send_Otp_OOredOORequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string App_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Otptype;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Opt_lenth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Mob_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Sent_by;
        
        public Create_Send_Otp_OOredOORequestBody() {
        }
        
        public Create_Send_Otp_OOredOORequestBody(string QID, string App_type, string Otptype, int Opt_lenth, string Mob_no, string email, string Sent_by) {
            this.QID = QID;
            this.App_type = App_type;
            this.Otptype = Otptype;
            this.Opt_lenth = Opt_lenth;
            this.Mob_no = Mob_no;
            this.email = email;
            this.Sent_by = Sent_by;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Create_Send_Otp_OOredOOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create_Send_Otp_OOredOOResponse", Namespace="http://tempuri.org/", Order=0)]
        public FooderSupportService.SMSWebService.Create_Send_Otp_OOredOOResponseBody Body;
        
        public Create_Send_Otp_OOredOOResponse() {
        }
        
        public Create_Send_Otp_OOredOOResponse(FooderSupportService.SMSWebService.Create_Send_Otp_OOredOOResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Create_Send_Otp_OOredOOResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Create_Send_Otp_OOredOOResult;
        
        public Create_Send_Otp_OOredOOResponseBody() {
        }
        
        public Create_Send_Otp_OOredOOResponseBody(string Create_Send_Otp_OOredOOResult) {
            this.Create_Send_Otp_OOredOOResult = Create_Send_Otp_OOredOOResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommunicateSoapChannel : FooderSupportService.SMSWebService.CommunicateSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommunicateSoapClient : System.ServiceModel.ClientBase<FooderSupportService.SMSWebService.CommunicateSoap>, FooderSupportService.SMSWebService.CommunicateSoap {
        
        public CommunicateSoapClient() {
        }
        
        public CommunicateSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommunicateSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicateSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FooderSupportService.SMSWebService.Send_EmailResponse FooderSupportService.SMSWebService.CommunicateSoap.Send_Email(FooderSupportService.SMSWebService.Send_EmailRequest request) {
            return base.Channel.Send_Email(request);
        }
        
        public string Send_Email(string QID, string App_type, string Sent_by, string To_Emails_List, string Cc_Email_List, string Email_Subject, string Email_Body, string My_Attached_File) {
            FooderSupportService.SMSWebService.Send_EmailRequest inValue = new FooderSupportService.SMSWebService.Send_EmailRequest();
            inValue.Body = new FooderSupportService.SMSWebService.Send_EmailRequestBody();
            inValue.Body.QID = QID;
            inValue.Body.App_type = App_type;
            inValue.Body.Sent_by = Sent_by;
            inValue.Body.To_Emails_List = To_Emails_List;
            inValue.Body.Cc_Email_List = Cc_Email_List;
            inValue.Body.Email_Subject = Email_Subject;
            inValue.Body.Email_Body = Email_Body;
            inValue.Body.My_Attached_File = My_Attached_File;
            FooderSupportService.SMSWebService.Send_EmailResponse retVal = ((FooderSupportService.SMSWebService.CommunicateSoap)(this)).Send_Email(inValue);
            return retVal.Body.Send_EmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Send_EmailResponse> FooderSupportService.SMSWebService.CommunicateSoap.Send_EmailAsync(FooderSupportService.SMSWebService.Send_EmailRequest request) {
            return base.Channel.Send_EmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Send_EmailResponse> Send_EmailAsync(string QID, string App_type, string Sent_by, string To_Emails_List, string Cc_Email_List, string Email_Subject, string Email_Body, string My_Attached_File) {
            FooderSupportService.SMSWebService.Send_EmailRequest inValue = new FooderSupportService.SMSWebService.Send_EmailRequest();
            inValue.Body = new FooderSupportService.SMSWebService.Send_EmailRequestBody();
            inValue.Body.QID = QID;
            inValue.Body.App_type = App_type;
            inValue.Body.Sent_by = Sent_by;
            inValue.Body.To_Emails_List = To_Emails_List;
            inValue.Body.Cc_Email_List = Cc_Email_List;
            inValue.Body.Email_Subject = Email_Subject;
            inValue.Body.Email_Body = Email_Body;
            inValue.Body.My_Attached_File = My_Attached_File;
            return ((FooderSupportService.SMSWebService.CommunicateSoap)(this)).Send_EmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FooderSupportService.SMSWebService.Send_normal_SMSResponse FooderSupportService.SMSWebService.CommunicateSoap.Send_normal_SMS(FooderSupportService.SMSWebService.Send_normal_SMSRequest request) {
            return base.Channel.Send_normal_SMS(request);
        }
        
        public string Send_normal_SMS(string QID, string App_type, FooderSupportService.SMSWebService.ArrayOfString mobile_no, string Sent_by, string Txt_sms) {
            FooderSupportService.SMSWebService.Send_normal_SMSRequest inValue = new FooderSupportService.SMSWebService.Send_normal_SMSRequest();
            inValue.Body = new FooderSupportService.SMSWebService.Send_normal_SMSRequestBody();
            inValue.Body.QID = QID;
            inValue.Body.App_type = App_type;
            inValue.Body.mobile_no = mobile_no;
            inValue.Body.Sent_by = Sent_by;
            inValue.Body.Txt_sms = Txt_sms;
            FooderSupportService.SMSWebService.Send_normal_SMSResponse retVal = ((FooderSupportService.SMSWebService.CommunicateSoap)(this)).Send_normal_SMS(inValue);
            return retVal.Body.Send_normal_SMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Send_normal_SMSResponse> FooderSupportService.SMSWebService.CommunicateSoap.Send_normal_SMSAsync(FooderSupportService.SMSWebService.Send_normal_SMSRequest request) {
            return base.Channel.Send_normal_SMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Send_normal_SMSResponse> Send_normal_SMSAsync(string QID, string App_type, FooderSupportService.SMSWebService.ArrayOfString mobile_no, string Sent_by, string Txt_sms) {
            FooderSupportService.SMSWebService.Send_normal_SMSRequest inValue = new FooderSupportService.SMSWebService.Send_normal_SMSRequest();
            inValue.Body = new FooderSupportService.SMSWebService.Send_normal_SMSRequestBody();
            inValue.Body.QID = QID;
            inValue.Body.App_type = App_type;
            inValue.Body.mobile_no = mobile_no;
            inValue.Body.Sent_by = Sent_by;
            inValue.Body.Txt_sms = Txt_sms;
            return ((FooderSupportService.SMSWebService.CommunicateSoap)(this)).Send_normal_SMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FooderSupportService.SMSWebService.Send_normal_SMS_ooredooResponse FooderSupportService.SMSWebService.CommunicateSoap.Send_normal_SMS_ooredoo(FooderSupportService.SMSWebService.Send_normal_SMS_ooredooRequest request) {
            return base.Channel.Send_normal_SMS_ooredoo(request);
        }
        
        public string Send_normal_SMS_ooredoo(string QID, string App_type, string mobile_no, string Sent_by, string Txt_sms) {
            FooderSupportService.SMSWebService.Send_normal_SMS_ooredooRequest inValue = new FooderSupportService.SMSWebService.Send_normal_SMS_ooredooRequest();
            inValue.Body = new FooderSupportService.SMSWebService.Send_normal_SMS_ooredooRequestBody();
            inValue.Body.QID = QID;
            inValue.Body.App_type = App_type;
            inValue.Body.mobile_no = mobile_no;
            inValue.Body.Sent_by = Sent_by;
            inValue.Body.Txt_sms = Txt_sms;
            FooderSupportService.SMSWebService.Send_normal_SMS_ooredooResponse retVal = ((FooderSupportService.SMSWebService.CommunicateSoap)(this)).Send_normal_SMS_ooredoo(inValue);
            return retVal.Body.Send_normal_SMS_ooredooResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Send_normal_SMS_ooredooResponse> FooderSupportService.SMSWebService.CommunicateSoap.Send_normal_SMS_ooredooAsync(FooderSupportService.SMSWebService.Send_normal_SMS_ooredooRequest request) {
            return base.Channel.Send_normal_SMS_ooredooAsync(request);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Send_normal_SMS_ooredooResponse> Send_normal_SMS_ooredooAsync(string QID, string App_type, string mobile_no, string Sent_by, string Txt_sms) {
            FooderSupportService.SMSWebService.Send_normal_SMS_ooredooRequest inValue = new FooderSupportService.SMSWebService.Send_normal_SMS_ooredooRequest();
            inValue.Body = new FooderSupportService.SMSWebService.Send_normal_SMS_ooredooRequestBody();
            inValue.Body.QID = QID;
            inValue.Body.App_type = App_type;
            inValue.Body.mobile_no = mobile_no;
            inValue.Body.Sent_by = Sent_by;
            inValue.Body.Txt_sms = Txt_sms;
            return ((FooderSupportService.SMSWebService.CommunicateSoap)(this)).Send_normal_SMS_ooredooAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesResponse FooderSupportService.SMSWebService.CommunicateSoap.Send_normal_SMS_Employees(FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesRequest request) {
            return base.Channel.Send_normal_SMS_Employees(request);
        }
        
        public string Send_normal_SMS_Employees(string QID, string App_type, string Emp_Qid_sapno, string Sent_by, string Txt_sms) {
            FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesRequest inValue = new FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesRequest();
            inValue.Body = new FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesRequestBody();
            inValue.Body.QID = QID;
            inValue.Body.App_type = App_type;
            inValue.Body.Emp_Qid_sapno = Emp_Qid_sapno;
            inValue.Body.Sent_by = Sent_by;
            inValue.Body.Txt_sms = Txt_sms;
            FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesResponse retVal = ((FooderSupportService.SMSWebService.CommunicateSoap)(this)).Send_normal_SMS_Employees(inValue);
            return retVal.Body.Send_normal_SMS_EmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesResponse> FooderSupportService.SMSWebService.CommunicateSoap.Send_normal_SMS_EmployeesAsync(FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesRequest request) {
            return base.Channel.Send_normal_SMS_EmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesResponse> Send_normal_SMS_EmployeesAsync(string QID, string App_type, string Emp_Qid_sapno, string Sent_by, string Txt_sms) {
            FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesRequest inValue = new FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesRequest();
            inValue.Body = new FooderSupportService.SMSWebService.Send_normal_SMS_EmployeesRequestBody();
            inValue.Body.QID = QID;
            inValue.Body.App_type = App_type;
            inValue.Body.Emp_Qid_sapno = Emp_Qid_sapno;
            inValue.Body.Sent_by = Sent_by;
            inValue.Body.Txt_sms = Txt_sms;
            return ((FooderSupportService.SMSWebService.CommunicateSoap)(this)).Send_normal_SMS_EmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpResponse FooderSupportService.SMSWebService.CommunicateSoap.Send_normal_SMS_ooredoo_Emp(FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpRequest request) {
            return base.Channel.Send_normal_SMS_ooredoo_Emp(request);
        }
        
        public string Send_normal_SMS_ooredoo_Emp(string QID, string App_type, string QID_Sap, string Sent_by, string Txt_sms) {
            FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpRequest inValue = new FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpRequest();
            inValue.Body = new FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpRequestBody();
            inValue.Body.QID = QID;
            inValue.Body.App_type = App_type;
            inValue.Body.QID_Sap = QID_Sap;
            inValue.Body.Sent_by = Sent_by;
            inValue.Body.Txt_sms = Txt_sms;
            FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpResponse retVal = ((FooderSupportService.SMSWebService.CommunicateSoap)(this)).Send_normal_SMS_ooredoo_Emp(inValue);
            return retVal.Body.Send_normal_SMS_ooredoo_EmpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpResponse> FooderSupportService.SMSWebService.CommunicateSoap.Send_normal_SMS_ooredoo_EmpAsync(FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpRequest request) {
            return base.Channel.Send_normal_SMS_ooredoo_EmpAsync(request);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpResponse> Send_normal_SMS_ooredoo_EmpAsync(string QID, string App_type, string QID_Sap, string Sent_by, string Txt_sms) {
            FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpRequest inValue = new FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpRequest();
            inValue.Body = new FooderSupportService.SMSWebService.Send_normal_SMS_ooredoo_EmpRequestBody();
            inValue.Body.QID = QID;
            inValue.Body.App_type = App_type;
            inValue.Body.QID_Sap = QID_Sap;
            inValue.Body.Sent_by = Sent_by;
            inValue.Body.Txt_sms = Txt_sms;
            return ((FooderSupportService.SMSWebService.CommunicateSoap)(this)).Send_normal_SMS_ooredoo_EmpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FooderSupportService.SMSWebService.Create_Send_Otp_OOredOOResponse FooderSupportService.SMSWebService.CommunicateSoap.Create_Send_Otp_OOredOO(FooderSupportService.SMSWebService.Create_Send_Otp_OOredOORequest request) {
            return base.Channel.Create_Send_Otp_OOredOO(request);
        }
        
        public string Create_Send_Otp_OOredOO(string QID, string App_type, string Otptype, int Opt_lenth, string Mob_no, string email, string Sent_by) {
            FooderSupportService.SMSWebService.Create_Send_Otp_OOredOORequest inValue = new FooderSupportService.SMSWebService.Create_Send_Otp_OOredOORequest();
            inValue.Body = new FooderSupportService.SMSWebService.Create_Send_Otp_OOredOORequestBody();
            inValue.Body.QID = QID;
            inValue.Body.App_type = App_type;
            inValue.Body.Otptype = Otptype;
            inValue.Body.Opt_lenth = Opt_lenth;
            inValue.Body.Mob_no = Mob_no;
            inValue.Body.email = email;
            inValue.Body.Sent_by = Sent_by;
            FooderSupportService.SMSWebService.Create_Send_Otp_OOredOOResponse retVal = ((FooderSupportService.SMSWebService.CommunicateSoap)(this)).Create_Send_Otp_OOredOO(inValue);
            return retVal.Body.Create_Send_Otp_OOredOOResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Create_Send_Otp_OOredOOResponse> FooderSupportService.SMSWebService.CommunicateSoap.Create_Send_Otp_OOredOOAsync(FooderSupportService.SMSWebService.Create_Send_Otp_OOredOORequest request) {
            return base.Channel.Create_Send_Otp_OOredOOAsync(request);
        }
        
        public System.Threading.Tasks.Task<FooderSupportService.SMSWebService.Create_Send_Otp_OOredOOResponse> Create_Send_Otp_OOredOOAsync(string QID, string App_type, string Otptype, int Opt_lenth, string Mob_no, string email, string Sent_by) {
            FooderSupportService.SMSWebService.Create_Send_Otp_OOredOORequest inValue = new FooderSupportService.SMSWebService.Create_Send_Otp_OOredOORequest();
            inValue.Body = new FooderSupportService.SMSWebService.Create_Send_Otp_OOredOORequestBody();
            inValue.Body.QID = QID;
            inValue.Body.App_type = App_type;
            inValue.Body.Otptype = Otptype;
            inValue.Body.Opt_lenth = Opt_lenth;
            inValue.Body.Mob_no = Mob_no;
            inValue.Body.email = email;
            inValue.Body.Sent_by = Sent_by;
            return ((FooderSupportService.SMSWebService.CommunicateSoap)(this)).Create_Send_Otp_OOredOOAsync(inValue);
        }
    }
}
